# Generated by Django 6.0 on 2025-12-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_quantity_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='code',
        ),
    ]
