# Generated by Django 6.0 on 2025-12-06 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, help_text='Enter the discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
