# Generated by Django 6.0 on 2025-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_discount_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/images/default_service.jpg', null=True, upload_to='services/images/'),
        ),
    ]
