# Generated by Django 6.0 on 2025-12-07 12:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Iranian format phone number(example: 09123456789)', max_length=128, null=True, region='IR', unique=True, verbose_name='Phone number'),
        ),
    ]
