# Generated by Django 6.0 on 2025-12-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('email', 'Email')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='store.service')),
            ],
        ),
    ]
