# Generated by Django 6.0 on 2025-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_servicefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('email', 'Email'), ('username', 'Username')], max_length=50),
        ),
    ]
