# Generated by Django 6.0 on 2025-12-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cartitem_extra_data_orderitem_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'service', 'extra_data')},
        ),
    ]
