# Generated by Django 6.0 on 2025-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
