# Generated by Django 6.0 on 2025-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orderitem_price_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, default='applications/images/default_application.jpg', null=True, upload_to='applications/images/'),
        ),
    ]
